### ISSUE TITLE
Please summarize project "status" in the README

### ISSUE THREAD

**Issue by BjarniRunar** [das-labor/neopg#65]
Hello!

This project looks very interesting! I am the lead developer of Mailpile (https://www.mailpile.is/) and we currently rely on GnuPG for our OpenPGP implementation. GnuPG is not the easiest of tools to work with, so I am always on the look out for alternatives. I agree with a lot of the "opinions" you've expressed and the direction you are taking, so this project is very interesting to me!

The one thing that is somewhat unclear to me, is what the *current* state of this project is.

Is it experimental? Is it alpha? Is it usable as a replacement for GnuPG, and if so in what cases?

It would be really helpful if things like this were explained with just a few sentences in the project README. Thanks!

(Another less important, but related question, has to do with the project itself. Is this a hobby project? Is this sponsored by your employer? If I decide I want to build on your work, how confident can I be that development and maintenance will continue?)

**Comment by lambdafu** [comment]
Thanks for your interest and support!  I agree that these are important questions that need better answers.  For now, the version number "0.0.4" should be some indication how I feel about the project :)
So, on the technical side, this is software under development, no promises made (except for the future).

The truth of the matter is that I am exploring how much interest there is in the community and what opportunities for funding there are.  The result of this exploratory phase will decide how to proceed.  But it will also decide what features are prioritized, and how the API and user interface will look like.  So I am very interested in hearing from you, and what your concerns are from the application side.  I have gotten some feedback at the 34c3, and at FOSDEM, but I am always looking out for more feedback, so I am very happy to hear from you!  Maybe we can arrange some opportunity to talk directly?

About your last question: I am currently unemployed, and focusing on NeoPG and OpenPGP fulltime, using up my savings (I was lucky to be funded to work on Free Software for many years, and I am willing and able to give back).  But this is not sustainable, so things need to change eventually.

I have applied for a grant to develop NeoPG fulltime.  If this goes through, I will be funded from September 2018 to April 2019, and I am willing to donate the time until September. This will give us time to find a more substantial base for the project. I will learn if the grant goes through in the beginning of June.  Until then I will also work on NeoPG as if the plan will work out!

**Comment by BjarniRunar** [comment]
Cool! Those are all good answers, thanks for clarifying.

I still encourage you to put something in the README for the next person who comes along!

I'd be very happy to chat with you directly. I'm almost always connected to IRC (BjarniRunar on Freenode, I hang out on #mailpile), and I can do Jit.si or Skype or something if you prefer. I am online most mornings and tue/thu/sat afternoons (other afternoons I am AFK with my daughter), CET time zone.
