### ISSUE TITLE
build or install broken on Ubuntu 18.04

### ISSUE THREAD

**Issue by deknos** [das-labor/neopg#81]
Hi, it seems the build or the installation under ubuntu  18.04 is broken.

When i clone the repo i do following things:
`git submodule update --init
 cd build
 cmake ..
 make && make test
 sudo make install
`
With v0.0.5 tag the library is created, but not installed, with master it seems the library isn't even created?

Any idea?

**Comment by lambdafu** [comment]
Please reopen if there is still an issue.
