### ISSUE TITLE
Release 0.0.6?

### ISSUE THREAD

**Issue by erictapen** [das-labor/neopg#97]
For the Nixpkgs upgrade to `0.0.5`, I somehow fail to run the tests. After a while I noticed, that I'm able to build neopg on current master just fine. Would it be possible to get a new release? That would make the version number of the package in Nixpkgs look more nice. Alternatively I'd bump neopg to `0.0.6pre2018-11-10` in https://github.com/NixOS/nixpkgs/pull/59942 .

**Comment by lambdafu** [comment]
Hi, and thanks! Why not? I just made a release of 0.0.6!

**Comment by erictapen** [comment]
Great, thanks!
